### ISSUE TITLE
Questions about dataset settings

### ISSUE THREAD

**Issue by MalignusCN** [ybarancan/TopologicalLaneGraph#2]
Hi, I've just read your paper, and felt like a very enlightening article. There are two questions I would like to ask now. 
First of all, which content should be downloaded for the data sets of nuScenes and Argoverse v2? In what format should the data set be filled in the root directory, and does the truth value of the topology need to be preprocessed first?
The second question is if we want to reproduce the results of this paper, what is the execution environment of our code, is there a .sh file or docker image, which can quickly install the code's running environment.
Thank you.

**Comment by ybarancan** [comment]
Hi, it is great to hear you liked the work. For NuScenes the whole dataset is necessary and for argoverse tracking and the map are enough. The format is the default format you will get when you extract the dataset. The true topologies need to be preprocessed first (please refer to step 3 in the steps to reproduce section). Unfortunately there is no .sh or docker file.

**Comment by MalignusCN** [comment]
I see, I will try it, thanks for your response~ Have a nice day
